#!/bin/bash
   
       #Author : Cedrick Kalukuta
       #Date : 03-04-2022
   
   ## ---------- script that provides steps to installing and configuring SonarQube on Centos 7 -----------------            
   
 echo "Run this script to install SonarQube on your Centos server. Please note that SonarQube does not work when you start it as a root user."
 echo
 sleep 3
 echo " Installation in progress..."
 sleep 2
 sudo yum update -y
 sudo yum install java-11-openjdk-devel java-11-openjdk wget unzip net-tools -y
 sleep 3
 echo
 cd /opt
 sleep 2
 echo
 sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899zip                              
 sleep 2
 echo
 sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899     
 sleep 3
 echo
 cd /opt/sonarqube-9.3.0.51899/bin/linux-x86-64
 sleep 2
 echo
 echo " System starting SonarQube..."
 echo
 ./sonar.sh start
 sleep 2
 echo " SonarQube successfully started and configured. You may now connect to the SonarQube server through the browser by following below steps: "
 echo
 echo " http://<your-ip-address>:9000 "
 echo " Please note that SonarQube uses port 9000. "
 echo
 echo "If you are unable to locate your ip address, run below command..."
 sleep 3
 sudo ifconfig
 echo
 echo " PS: Please note that some servers may have firewall enabled. If you are unable to connect to the SonarQube browser, be sure to run the below command to open port 9000.The # must be removed for the commands to run successfully."
  
  
 #sudo firewall-cmd --permanent --add-port=9000/tcp
 #sudo firewall-cmd --reload